[package]
name = "compiler2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
fs_extra = "1.3.0"
inter = { path = "../inter" }
itertools = "0.13.0"
uuid = { version = "1.11.0", features = ["v4"] }
zip = "2.2.0"
zip-extensions = "0.8.1"
