[package]
name = "mem_opt"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0.95"
shared = { path = "../shared" }
asm_compiler = { path = "../asm_compiler" }
inter = { path = "../inter" }
uuid = "1.15.1"
itertools = "0.14.0"
